INSERT INTO ARTIST (NAME) VALUES ('Kanye West');
INSERT INTO GENRE (NAME, DESCRIPTION) VALUES ('Hip Hop', 'test');
INSERT INTO PLAYLIST (NAME, DESCRIPTION, ARTWORK) VALUES ('sad', 'when youre sad', 'unknown');
INSERT INTO TRACK (NAME, DURATION, LYRICS) VALUES ('marvins room', 3, 'lyrics');