INSERT INTO ARTIST (NAME) VALUES ('Kanye West');
INSERT INTO GENRE (NAME, DESCRIPTION) VALUES ('Hip Hop', 'test');
INSERT INTO TRACK (NAME, DURATION, LYRICS) VALUES ('marvins room', 3, 'lyrics');
INSERT INTO USER (USER_NAME, PASSWORD, AUTH) VALUES ('Nick', 'password', 'none');
INSERT INTO PLAYLIST (NAME, DESCRIPTION, ARTWORK, USER_ID) VALUES ('sad', 'when youre sad', 'unknown', 1);
INSERT INTO PLAYLIST_TRACK (PLAYLIST_ID, TRACK_ID) VALUES (null, null);
INSERT INTO ALBUM (NAME, ARTIST_ID, GENRE_ID, COVER) VALUES ('Scorpion', 1, 1, 'none');